from typing import TypedDict, List, Dict, Any, Optional

class AgentState(TypedDict, total=False):
    original_question: str
    decomposed_questions: List[str] # If the question was broken down
    current_question: str # The question currently being processed
    retrieved_context: List[str] # Chunks retrieved from RRF
    draft_answer: str # The draft answer generated by the Evidence Builder
    final_answer: str # The final verified answer
    routing_decision: str # e.g., 'direct_answer', 'vector_search', 'graph_search'
    depth: Optional[str] # 'quick' | 'summary' | 'deep'
    verifier_enabled: bool # If False, skip verifier node completely
    verification_passed: bool # True if the Verifier accepts the draft
    chat_history: List[Dict[str, str]] # Kept for backwards compatibility
    memory_context: str # The formatted recent history and facts
    conversation_id: str # ID of the current conversation
    # Personal document retrieval — when set the retriever EXCLUSIVELY searches
    # the personal document; the shared corpus path is not touched.
    document_id: Optional[str]  # Active personal document ID (None = no document attached)
    user_id: Optional[str]      # Authenticated user's ID (needed for 3-field isolation filter)
